import api.user_Test 
import api.collab_Test 
import api.youtube_video_Test 
import api.meal_Test
import api.workout_Test

api.user_Test.GetAll()
api.user_Test.GetSingle("1")
api.user_Test.Post()
api.user_Test.Delete("1")
api.user_Test.Put("1")
api.user_Test.PostLogin()
print()
print()
print()
print()
print("USER TABLE TESTS: ",api.user_Test.userPC , "/6 tests passed")
input()
print()
print()
print()
print()
api.collab_Test.GetAll()
api.collab_Test.GetSingle("1")
#api.collab_Test.Delete()
api.collab_Test.Post()
api.collab_Test.Put("50")
print()
print()
print()
print()
print("COLLABORATOR TABLE TESTS: ",api.collab_Test.collabPC , "/4 tests passed")
input()
print()
print()
print()
api.youtube_video_Test.GetAll()
api.youtube_video_Test.GetSingle("1")
api.youtube_video_Test.Delete("50")
api.youtube_video_Test.Post()
api.youtube_video_Test.Put("50")
print()
print()
print()
print()
print("YOUTUBE VIDEO TABLE TESTS: ",api.youtube_video_Test.youtubePC , "/5 tests passed")
input()
print()
print()
print()
api.meal_Test.GetAll()
api.meal_Test.GetSingle("11")
api.meal_Test.Delete("11")
api.meal_Test.Post()
api.meal_Test.Put("11")
print()
print()
print()
print()
print("MEAL TABLE TESTS: ",api.meal_Test.mealPC , "/5 tests passed")
input()
print()
print()
print()
api.workout_Test.GetAll()
api.workout_Test.GetSingle("1")
api.workout_Test.Delete("10")
api.workout_Test.Post()
api.workout_Test.Put("10")
print()
print()
print()
print()
print("WORKOUT TABLE TESTS: ",api.workout_Test.workoutPC , "/5 tests passed")
input()
print()
print()
print()
print()
totalPassed = api.user_Test.userPC + api.collab_Test.collabPC + api.youtube_video_Test.youtubePC + api.meal_Test.mealPC + api.workout_Test.workoutPC
print()
print()
print()
print()
print("TOTAL PASSED: ", totalPassed, "/25")


